[package]
name = "clawless-cli"
description = "Generate and develop CLIs with Clawless"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "clawless"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
clawless = { workspace = true }
getset = { workspace = true }

[dev-dependencies]
trycmd = "0.15.9"

[build-dependencies]
convert_case = "0.8.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
