[[label]]
name = "good-first-issue"
description = "Good issue for newcomers - mentoring available"
color = "#4ade80"

[[group]]
prefix = "A-"
colors = { tailwind = "lime" }
labels = [
  { name = "clawless", description = "An issue related to clawless" },
  { name = "cli", description = "An issue related to clawless-cli" },
  { name = "docs", description = "An issue related to the documentation" },
  { name = "macros", description = "An issue related to clawless-derive" },
  { name = "github-actions", description = "An issue related to GitHub Actions" },
]

[[group]]
prefix = "C-"
colors = { tailwind = "red" }
labels = [
  { name = "bug", description = "Report a new bug" },
  { name = "dependency", description = "Change or update a dependency" },
  { name = "documentation", description = "Improve the documentation" },
  { name = "feature", description = "Request a new feature", aliases = [
    "feature-request",
  ] },
]

[[group]]
prefix = "R-"
colors = { tailwind = "slate" }
labels = [
  { name = "added", description = "Add a new feature to the release notes" },
  { name = "changed", description = "Add a change in existing functionality to the release notes" },
  { name = "deprecated", description = "Add a soon-to-be removed feature to the release notes" },
  { name = "fixed", description = "Add a fixed bug to the release notes" },
  { name = "ignore", description = "Do not add this pull request to the release notes" },
  { name = "removed", description = "Add a now removed feature to the release notes" },
  { name = "security", description = "Add a vulnerability warning to the release notes" },
]
