[package]
name = "clawless-cutie"
description = "A framework to build command-line applications with Rust"
authors = ["aonyx"]
edition = "2021"
version = "0.0.0"

# Earthly installs cargo-sweep@0.7.0 in CI, which requires 1.78.0.
rust-version = "1.78.0"

repository = "https://github.com/jdno/clawless.git"

[dependencies]

[dev-dependencies]
